accepted = [
  "0BSD",
  "AGPL-3.0",
  "AGPL-3.0-only",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "LGPL-2.1-or-later",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
targets = ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]
ignore-dev-dependencies = true
workarounds = ["chrono", "prost", "ring", "rustls", "rustix"]
